server:
  port: 8888
spring:
  kafka:
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl.endpoint.identification.algorithm:
      security.protocol: SSL
    ssl:
      protocol: SSL
      trust-store-location: file:truststore-cluster-1.jks
      trust-store-password: p@ssw0rd
    consumer:
      bootstrap-servers: amqstreams-cluster-1-kafka-bootstrap-streams-playground-1.apps.ocp.lab.redhat.com:443
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
      properties:
        spring.json.trusted.packages: "com.redhat.apicuriokafkademo"
        apicurio:
          registry:
            use-specific-avro-reader: true
            url: http://apicurioregistry1.streams-playground-1.apps.ocp.lab.redhat.com/api