server:
  port: 8080
spring:
  kafka:
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl.endpoint.identification.algorithm:
      security.protocol: SSL
    ssl:
      protocol: SSL
      trust-store-location: file:truststore-cluster-1.jks
      trust-store-password: p@ssw0rd
    producer:
      bootstrap-servers: amqstreams-cluster-1-kafka-bootstrap-streams-playground-1.apps.ocp.lab.redhat.com:443
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
      properties:
        apicurio:
          registry:
            url: http://apicurioregistry1.streams-playground-1.apps.ocp.lab.redhat.com/api
            artifact-id: io.apicurio.registry.utils.serde.strategy.TopicIdStrategy