server:
  port: 8081
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: spring-example-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      properties:
        spring.json.trusted.packages: "io.apicurio.example"
        apicurio:
          registry:
            url: http://localhost:8181/apis/registry/v2
            use-specific-avro-reader: true
            # artifact.group-id: io.apicurio.example
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer
      properties:
        apicurio:
          registry:
            url: http://localhost:8181/apis/registry/v2
            artifact-resolver-strategy: io.apicurio.registry.serde.avro.strategy.RecordIdStrategy
            # auto-register: true
            find-latest: true
            artifact.group-id: io.apicurio.example